# In tasks/ssl_httpd.yml

- name: Crea directory per certificati
  file:
    path: /etc/httpd/ssl
    state: directory
    mode: '0755'

- name: Verifica esistenza certificato
  stat:
    path: /etc/httpd/ssl/cert.pem
  register: ssl_cert

- name: Genera certificato autofirmato
  command: >
    openssl req -new -newkey rsa:2048 -days 365 -nodes -x509
    -subj "/C=IT/ST=Italy/L=Rome/O=MyCompany/OU=IT/CN=example.com"
    -keyout /etc/httpd/ssl/key.pem
    -out /etc/httpd/ssl/cert.pem
  when: not ssl_cert.stat.exists

- name: Configura VirtualHost SSL su porta 444
  copy:
    dest: /etc/httpd/conf.d/ssl.conf
    content: |
      Listen 444
      <VirtualHost *:444>
          ServerAdmin admin@example.com
          DocumentRoot /var/www/html
          
          SSLEngine on
          SSLCertificateFile /etc/httpd/ssl/cert.pem
          SSLCertificateKeyFile /etc/httpd/ssl/key.pem
          
          SSLCipherSuite ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
          SSLProtocol -all +TLSv1.2 +TLSv1.3

          ErrorLog "logs/ssl_error_log"
          CustomLog "logs/ssl_access_log" combined

          <IfModule mod_security2.c>
              SecRuleEngine On
              SecRequestBodyAccess On
          </IfModule>
      </VirtualHost>
    mode: '0644'
  when: inventory_hostname in groups['workers']

- name: Configura Bilanciatore Apache in HTTPS sulla 444
  copy:
    dest: /etc/httpd/conf.d/load_balancer_ssl.conf
    content: |
      # 1. Diciamo ad Apache di ascoltare sulla 444
      Listen 444

      # 2. Definizione dei server backend (porta 81)
      <Proxy "balancer://mycluster_ssl">
          BalancerMember "http://172.16.106.131:81"
          BalancerMember "http://172.16.106.132:81"
          ProxySet lbmethod=byrequests
      </Proxy>

      # 3. Configurazione del VirtualHost SSL
      <VirtualHost *:444>
          ServerName {{ lb_ip_address }}

          SSLEngine on
          # Usa i certificati generati precedentemente
          SSLCertificateFile /etc/httpd/ssl/cert.pem
          SSLCertificateKeyFile /etc/httpd/ssl/key.pem

          # 4. Inoltro del traffico al cluster
          ProxyPass "/" "balancer://mycluster_ssl/"
          ProxyPassReverse "/" "balancer://mycluster_ssl/"

          # Header utili per i log dei backend
          ProxyPreserveHost On
          RequestHeader set X-Forwarded-Proto "https"
          RequestHeader set X-Forwarded-Port "444"

          ErrorLog "logs/balancer_ssl_error_log"
          CustomLog "logs/balancer_ssl_access_log" combined
      </VirtualHost>
    mode: '0644'
  when: inventory_hostname in groups['loadbalancer']

#correggi i permessi selinux per la nuova porta 444
- name: Configura SELinux per consentire ad Apache di ascoltare sulla porta 444
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes