#installa mod_ssl
- name: installa mod_ssl
  dnf:
    name: mod_ssl
    state: present
    update_cache: true
#stampa messaggio di conferma
- name: mostra messaggio di conferma per l'installazione di mod_ssl
  debug:
    msg: "mod_ssl è stato installato correttamente."

#installa mod_security
- name: installa mod_security
  dnf:
    name: mod_security
    state: present
    update_cache: true
#stampa messaggio di conferma
- name: mostra messaggio di conferma per l'installazione di mod_security
  debug:
    msg: "mod_security è stato installato correttamente."

#crea la directory per i certificati SSL
- name: crea la directory per i certificati SSL
  file:
    #path della directory
    path: /etc/httpd/ssl
    state: directory
    mode: '0755'

#verifica se il certificato esiste già
- name: verifica se il certificato SSL esiste
  stat:
    path: /etc/httpd/ssl/cert.pem
  register: ssl_cert

#se esiste non fare nulla, altrimenti genera il certificato
- name: genera il certificato autofirmato
  command: >
    openssl req -new -newkey rsa:2048 -days 365 -nodes -x509
    -subj "/C=IT/ST=Italy/L=Rome/O=MyCompany/OU=IT/CN=example.com"
    -keyout /etc/httpd/ssl/key.pem
    -out /etc/httpd/ssl/cert.pem
  when: not ssl_cert.stat.exists
  args:
    creates: /etc/httpd/ssl/cert.pem

#configura Apache per usare SSL
- name: configura Apache per usare SSL
  copy:
    content: |
      <VirtualHost *:444>
          ServerAdmin admin@example.com
          DocumentRoot /var/www/html
          SSLEngine on
          SSLCertificateFile /etc/httpd/ssl/cert.pem
          SSLCertificateKeyFile /etc/httpd/ssl/key.pem
      </VirtualHost>
    dest: /etc/httpd/conf.d/ssl.conf
    mode: '0644'

#se non esiste crea la cartella /var/www/html
- name: crea la cartella /var/www/html se non esiste
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

#crea la pagina di benvenuto in HTTPS
- name: crea la pagina di benvenuto in HTTPS
  copy:
    content: |
      <!DOCTYPE html>
      <html>
        <head>
          <title>Benvenuto in Apache HTTPS</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              text-align: center;
              margin-top: 50px;
            }
          </style>
        </head>
        <body>
          <h1>Successo! Apache &egrave configurato in HTTPS.</h1>
          <p>Questa pagina &egrave stata generata da Ansible.</p>
        </body>
      </html>
    dest: /var/www/html/index.html